export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_CURRENT_INGREDIENT = 'SET_CURRENT_INGREDIENT'; 
export const SET_ORDER = 'SET_ORDER';