export const SET_INGREDIENTS: 'SET_INGREDIENTS' = 'SET_INGREDIENTS';
export const SET_CURRENT_INGREDIENT: 'SET_CURRENT_INGREDIENT' = 'SET_CURRENT_INGREDIENT';
export const SET_ORDER: 'SET_ORDER' = 'SET_ORDER';

export const GET_INGREDIENTS_REQUEST: 'GET_INGREDIENTS_REQUEST' = 'GET_INGREDIENTS_REQUEST';
export const GET_INGREDIENTS_SUCCESS: 'GET_INGREDIENTS_SUCCESS' = 'GET_INGREDIENTS_SUCCESS';
export const GET_INGREDIENTS_FAILURE: 'GET_INGREDIENTS_FAILURE' = 'GET_INGREDIENTS_FAILURE';
