export const ORDER_FEED_WS_CONNECT: 'ORDER_FEED_WS_CONNECT' = 'ORDER_FEED_WS_CONNECT';
export const ORDER_FEED_WS_DISCONNECT: 'ORDER_FEED_WS_DISCONNECT' = 'ORDER_FEED_WS_DISCONNECT';
export const ORDER_FEED_WS_CONNECTING: 'ORDER_FEED_WS_CONNECTING' = 'ORDER_FEED_WS_CONNECTING';
export const ORDER_FEED_WS_OPEN: 'ORDER_FEED_WS_OPEN' = 'ORDER_FEED_WS_OPEN';
export const ORDER_FEED_WS_CLOSE: 'ORDER_FEED_WS_CLOSE' = 'ORDER_FEED_WS_CLOSE';
export const ORDER_FEED_WS_ERROR: 'ORDER_FEED_WS_ERROR' = 'ORDER_FEED_WS_ERROR';
export const ORDER_FEED_WS_MESSAGE: 'ORDER_FEED_WS_MESSAGE' = 'ORDER_FEED_WS_MESSAGE';

export const ORDER_HISTORY_WS_CONNECT: 'ORDER_HISTORY_WS_CONNECT' = 'ORDER_HISTORY_WS_CONNECT';
export const ORDER_HISTORY_WS_DISCONNECT: 'ORDER_HISTORY_WS_DISCONNECT' = 'ORDER_HISTORY_WS_DISCONNECT';
export const ORDER_HISTORY_WS_CONNECTING: 'ORDER_HISTORY_WS_CONNECTING' = 'ORDER_HISTORY_WS_CONNECTING';
export const ORDER_HISTORY_WS_OPEN: 'ORDER_HISTORY_WS_OPEN' = 'ORDER_HISTORY_WS_OPEN';
export const ORDER_HISTORY_WS_CLOSE: 'ORDER_HISTORY_WS_CLOSE' = 'ORDER_HISTORY_WS_CLOSE';
export const ORDER_HISTORY_WS_ERROR: 'ORDER_HISTORY_WS_ERROR' = 'ORDER_HISTORY_WS_ERROR';
export const ORDER_HISTORY_WS_MESSAGE: 'ORDER_HISTORY_WS_MESSAGE' = 'ORDER_HISTORY_WS_MESSAGE';